Missing () while calling lower()
Fixing bug causing TypeError while setting ACLs
 TypeError: cannot serialize <built-in method lower of str object at 0x2133570> (type builtin_function_or_method)